In [1]:
from pathlib import Path

import pandas as pd

TABLES = Path("../pipeline_tables")   # the stage summary tables this repo ships

In [2]:
df = pd.read_csv(TABLES / "verification_summary.tsv", sep="\t")

In [3]:
df

,sample,asm_num_seqs,asm_sum_len,asm_max_len,asm_n_chromosomes,asm_chr_circular,asm_chr_coverage,mapped_pct,properly_paired_pct,supplementary_alignments,...,kbt_illumina_ST,kbt_illumina_K_locus,kbt_illumina_K_locus_confidence,kbt_species_concordant,kbt_ST_concordant,kbt_K_locus_concordant,kraken2_status,kraken2_dominant_species,kraken2_klebsiella_pct,kraken2_flags
0,INF001.1,2,5658601,5571678,1,Y,79,98.80,98.63,676,...,ST3090,KL3,Typeable,YES,YES,YES,PASS,Klebsiella variicola,97.29,NaN
1,INF001.2,4,5675701,5243603,1,Y,117,82.22,79.41,5411,...,ST3090,KL3,Typeable,NO,NO,NO,PASS,Klebsiella pneumoniae,98.39,NaN
2,INF002,4,5733472,5425252,1,Y,117,99.92,99.76,969,...,ST133,KL116,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,94.34,NaN
3,INF003,3,5534700,5232856,1,Y,157,97.09,96.77,352,...,ST323,KL21,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,97.32,NaN
4,INF004,3,5359970,5266566,1,Y,139,99.42,99.05,1402,...,ST345,KL15,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,95.54,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311,KSB2_8D,7,5662121,5217587,1,Y,76,99.96,99.66,770,...,ST643,KL38,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,88.08,NaN
312,KSB2_9B,5,5609366,5276824,1,Y,67,99.91,98.34,9988,...,ST25,KL2,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,93.79,NaN
313,KSB2_9C,2,5318223,5184781,1,Y,82,99.58,99.36,360,...,ST788,KL8,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,95.93,NaN
314,KSB2_10C.1,3,5484763,5260662,1,Y,68,99.51,99.27,356,...,ST661,KL24,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,95.82,NaN
315,KSB2_10C.2,3,5033183,4865102,1,Y,153,11.79,7.72,617,...,ST661,KL24,Typeable,NO,NO,NO,FAIL,Klebsiella pneumoniae,0.66,NON_KLEBSIELLA_CONTAMINATION: Escherichia 85.7...

In [4]:
# quick first pass - everything that's just fine
# asm_n_chromosomes == 1, mapped_pct >= 95, kbt_K_locus_concordant == YES, kraken2_status == PASS

df_filtered = df[(df['asm_n_chromosomes'] == 1) & (df['mapped_pct'] >= 95) & (df['kbt_K_locus_concordant'] == 'YES') & (df['kraken2_status'] == 'PASS')]
pass_samples = df_filtered['sample'].tolist()

In [5]:
df_filtered

,sample,asm_num_seqs,asm_sum_len,asm_max_len,asm_n_chromosomes,asm_chr_circular,asm_chr_coverage,mapped_pct,properly_paired_pct,supplementary_alignments,...,kbt_illumina_ST,kbt_illumina_K_locus,kbt_illumina_K_locus_confidence,kbt_species_concordant,kbt_ST_concordant,kbt_K_locus_concordant,kraken2_status,kraken2_dominant_species,kraken2_klebsiella_pct,kraken2_flags
0,INF001.1,2,5658601,5571678,1,Y,79,98.80,98.63,676,...,ST3090,KL3,Typeable,YES,YES,YES,PASS,Klebsiella variicola,97.29,NaN
2,INF002,4,5733472,5425252,1,Y,117,99.92,99.76,969,...,ST133,KL116,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,94.34,NaN
3,INF003,3,5534700,5232856,1,Y,157,97.09,96.77,352,...,ST323,KL21,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,97.32,NaN
4,INF004,3,5359970,5266566,1,Y,139,99.42,99.05,1402,...,ST345,KL15,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,95.54,NaN
5,INF005,8,5985259,5570473,1,Y,67,99.81,99.41,1821,...,ST641,KL60,Typeable,YES,YES,YES,PASS,Klebsiella variicola,94.38,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,KSB2_8C,1,5203622,5203622,1,Y,86,99.37,99.16,366,...,ST2267,KL127,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,95.46,NaN
311,KSB2_8D,7,5662121,5217587,1,Y,76,99.96,99.66,770,...,ST643,KL38,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,88.08,NaN
312,KSB2_9B,5,5609366,5276824,1,Y,67,99.91,98.34,9988,...,ST25,KL2,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,93.79,NaN
313,KSB2_9C,2,5318223,5184781,1,Y,82,99.58,99.36,360,...,ST788,KL8,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,95.93,NaN
314,KSB2_10C.1,3,5484763,5260662,1,Y,68,99.51,99.27,356,...,ST661,KL24,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,95.82,NaN

In [6]:
# Take a look at the rest and decide manually
df[~df['sample'].isin(pass_samples)]

,sample,asm_num_seqs,asm_sum_len,asm_max_len,asm_n_chromosomes,asm_chr_circular,asm_chr_coverage,mapped_pct,properly_paired_pct,supplementary_alignments,...,kbt_illumina_ST,kbt_illumina_K_locus,kbt_illumina_K_locus_confidence,kbt_species_concordant,kbt_ST_concordant,kbt_K_locus_concordant,kraken2_status,kraken2_dominant_species,kraken2_klebsiella_pct,kraken2_flags
1,INF001.2,4,5675701,5243603,1,Y,117,82.22,79.41,5411,...,ST3090,KL3,Typeable,NO,NO,NO,PASS,Klebsiella pneumoniae,98.39,NaN
35,INF050,4,5603387,5228931,1,Y,92,94.90,94.57,821,...,ST323,KL21,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,94.81,NaN
51,INF071.2,2,5602428,5362695,1,Y,51,87.89,86.87,3107,...,ST607,KL48,Typeable,YES,NO,NO,PASS,Klebsiella pneumoniae,97.44,NaN
67,INF092.2,5,5024780,4861420,1,Y,40,16.85,11.36,1276,...,ST2415,KL131,Typeable,NO,NO,NO,FAIL,Klebsiella pneumoniae,1.41,NON_KLEBSIELLA_CONTAMINATION: Enterobacter 95....
69,INF093.2,3,5567164,5228924,1,Y,114,91.77,91.19,1270,...,ST323,KL21,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,98.47,NaN
70,INF096,30,5959360,2808496,0,NaN,NaN,99.94,99.42,2186,...,ST603,KL22,Typeable,YES,YES,NO,PASS,Klebsiella pneumoniae,97.28,NaN
88,INF117.2,3,5579813,5323609,1,Y,102,90.61,89.48,3500,...,ST3045,KL146,Typeable,YES,NO,NO,PASS,Klebsiella pneumoniae,95.25,NaN
125,INF184,2,5318229,5168645,1,Y,163,99.98,99.73,403,...,ST3062,KL124,Typeable,YES,YES,YES,FAIL,Klebsiella pneumoniae,92.57,NON_KLEBSIELLA_CONTAMINATION: Escherichia 5.9%
126,INF186,6,10640892,5168628,2,"Y,Y","285,215",99.27,99.09,204,...,ST480,KL52,Typeable,NO,YES,NO,FAIL,Klebsiella pneumoniae,95.96,MIXED_KLEBSIELLA: 2 species each ≥ 20.0% (Kleb...
131,INF195,2,5269757,5087395,1,Y,173,99.98,99.84,460,...,ST414,KL123,Typeable,YES,YES,YES,FAIL,Klebsiella quasipneumoniae,97.33,MIXED_KLEBSIELLA: 2 species each ≥ 20.0% (Kleb...
140,INF205,4,5524772,3151798,0,NaN,NaN,99.96,99.78,654,...,ST3049,KL55,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,97.32,NaN
146,INF216,13,10667759,4060058,1,N,275,99.86,99.67,2034,...,ST3079,KL53,Typeable,YES,NO,YES,FAIL,Klebsiella pneumoniae,98.18,MIXED_KLEBSIELLA: 2 species each ≥ 20.0% (Kleb...
174,INF255.2_v2,746,15674009,278058,0,NaN,NaN,97.26,96.16,19662,...,ST29,KL30,Typeable,YES,NO,NO,PASS,Klebsiella pneumoniae,83.20,NaN
182,INF262_v2,30,12392096,5802241,2,"Y,Y","30,76",99.62,98.87,3696,...,NON_KPSC,NON_KPSC,NON_KPSC,YES,YES,YES,FAIL,Klebsiella variicola,89.98,MIXED_KLEBSIELLA: 2 species each ≥ 20.0% (Kleb...
187,INF269,3,5516525,5381309,1,Y,356,99.97,99.59,425,...,ST13,KL3,Typeable,YES,YES,YES,FAIL,Klebsiella pneumoniae,90.59,NON_KLEBSIELLA_CONTAMINATION: Escherichia 5.4%
201,INF294,23,6001194,5242724,1,N,175,99.70,99.00,1969,...,ST37,KL15,Typeable,YES,YES,NO,PASS,Klebsiella pneumoniae,98.42,NaN
229,INF340,3,5589711,5277849,1,Y,246,93.58,93.27,541,...,ST45,KL24,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,98.31,NaN
247,KSB1_2F,2,5526809,5521077,1,Y,139,99.84,99.47,274,...,ST2594,KL134,Typeable,YES,YES,YES,FAIL,Klebsiella variicola,96.93,MIXED_KLEBSIELLA: 2 species each ≥ 20.0% (Kleb...
249,KSB1_2I,4,10504723,5511561,2,"Y,Y","63,11",99.38,99.01,291,...,ST2993,KL151,Typeable,YES,YES,YES,FAIL,Klebsiella variicola,65.94,NON_KLEBSIELLA_CONTAMINATION: Escherichia 22.4%
257,KSB1_3I,4,5580319,5194784,1,Y,66,97.67,97.12,546,...,ST1548,KL170,Typeable,YES,YES,YES,FAIL,Klebsiella quasipneumoniae,94.15,MIXED_KLEBSIELLA: 2 species each ≥ 20.0% (Kleb...
267,KSB1_5C,7,5543042,5050285,1,N,135,94.98,93.87,1919,...,ST3169,KL31,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,94.56,NaN
272,KSB1_6D_v2,2,5444361,5223207,1,N,89,99.50,99.13,786,...,ST414,KL123,Typeable,YES,YES,YES,FAIL,Klebsiella quasipneumoniae,93.89,MIXED_KLEBSIELLA: 2 species each ≥ 20.0% (Kleb...
277,KSB1_7B.2,3,5050538,4791233,1,Y,216,13.81,9.60,410,...,ST5168,KL21,Typeable,NO,NO,NO,FAIL,Klebsiella pneumoniae,3.95,NON_KLEBSIELLA_CONTAMINATION: Escherichia 76.4...
284,KSB1_8E.2,2,5316289,5172158,1,Y,47,12.60,8.49,499,...,ST2994,KL35,Typeable,NO,NO,NO,FAIL,Klebsiella variicola,7.41,NON_KLEBSIELLA_CONTAMINATION: Escherichia 86.9...
298,KSB2_4A,8,10768378,5141356,2,"Y,Y","84,191",98.26,97.71,351,...,ST1191,KL13,Typeable,YES,YES,YES,FAIL,Klebsiella quasipneumoniae,29.54,NON_KLEBSIELLA_CONTAMINATION: Escherichia 58.9...
301,KSB2_5D_v2,103,10397488,1714328,0,NaN,NaN,99.18,98.77,4044,...,ST35-2LV,KL53,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,94.29,NaN
304,KSB2_6B.2,3,4819632,4757536,1,Y,133,11.69,7.68,457,...,ST215,KL16,Typeable,NO,NO,NO,FAIL,Klebsiella pneumoniae,6.67,NON_KLEBSIELLA_CONTAMINATION: Escherichia 81.0...
315,KSB2_10C.2,3,5033183,4865102,1,Y,153,11.79,7.72,617,...,ST661,KL24,Typeable,NO,NO,NO,FAIL,Klebsiella pneumoniae,0.66,NON_KLEBSIELLA_CONTAMINATION: Escherichia 85.7...

In [7]:
# Manual decisions:
# INF001.2 -> variant, other ok, FAIL
# INF050 -> mapping at 0.1% below threshold, other ok, PASS
# INF071.2, INF092.2, INF093.2 -> variant, other ok, FAIL
# INF096 - > 30 contigs -> retry assembly with other params (flye-meta)
# INF117.2 -> variant, other ok, FAIL
# INF184 -> false positive e. coli cont (plasmid), PASS
# INF186 -> mixed klebsiella, decontaminate and reassemble
# INF195 -> kraken2 says mixed klebsiella, but no other evidence, PASS for now but check vs external reference
# INF205 -> no chromosome, retry assembly with other params (flye-meta)
# INF216 -> mixed klebsiella, decontaminate and reassemble
# INF255.2_v2 -> variant, other ok, FAIL
# INF262_v2 -> mixed klebsiella, decontaminate and reassemble
# INF269 -> false positive e. coli cont (plasmid), PASS
# INF294 -> k_locus not concordant, 23 contigs, retry assembly with other params (flye-meta)
# INF340 -> mapped_pct 1.5% below threshold, other ok, PASS
# KSB1_2F -> kraken2 says mixed klebsiella, but no other evidence, PASS for now but check vs external reference
# KSB1_2I -> contaminated with e. coli, decontaminate and reassemble
# KSB1_3I -> kraken2 says mixed klebsiella, but no other evidence, PASS for now but check vs external reference
# KSB1_5C -> mapping_pct 0.02% below threshold, other ok, PASS
# KSB1_6D_v2 -> kraken2 says mixed klebsiella, but no other evidence, PASS for now but check vs external reference
# KSB1_7B.2 -> variant, other ok, FAIL
# KSB1_8E.2 -> variant, other ok, FAIL
# KSB2_4A -> contaminated with e. coli, decontaminate and reassemble
# KSB2_5D_v2 -> bad assembly, retry assembly with other params (flye-meta)
# KSB2_6B.2 -> variant, other ok, FAIL
# KSB2_10C.2 -> variant, other ok, FAIL

In [8]:
# Manually go through all morphological differece samples and decide which ones to keep
df_variants = df[df['sample'].str.endswith(('.2', '.2_v2', '.1', '.1_v2'))]

In [9]:
df_variants

,sample,asm_num_seqs,asm_sum_len,asm_max_len,asm_n_chromosomes,asm_chr_circular,asm_chr_coverage,mapped_pct,properly_paired_pct,supplementary_alignments,...,kbt_illumina_ST,kbt_illumina_K_locus,kbt_illumina_K_locus_confidence,kbt_species_concordant,kbt_ST_concordant,kbt_K_locus_concordant,kraken2_status,kraken2_dominant_species,kraken2_klebsiella_pct,kraken2_flags
0,INF001.1,2,5658601,5571678,1,Y,79,98.80,98.63,676,...,ST3090,KL3,Typeable,YES,YES,YES,PASS,Klebsiella variicola,97.29,NaN
1,INF001.2,4,5675701,5243603,1,Y,117,82.22,79.41,5411,...,ST3090,KL3,Typeable,NO,NO,NO,PASS,Klebsiella pneumoniae,98.39,NaN
50,INF071.1,3,5557597,5309915,1,Y,33,99.99,99.78,628,...,ST607,KL48,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,98.05,NaN
51,INF071.2,2,5602428,5362695,1,Y,51,87.89,86.87,3107,...,ST607,KL48,Typeable,YES,NO,NO,PASS,Klebsiella pneumoniae,97.44,NaN
64,INF091.1,2,5508939,5348829,1,Y,147,98.47,98.21,663,...,ST45,KL24,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,92.63,NaN
65,INF091.2,2,5600852,5348825,1,Y,191,99.99,99.79,726,...,ST45,KL24,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,95.31,NaN
66,INF092.1,1,5340412,5340412,1,Y,171,99.26,99.02,755,...,ST2415,KL131,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,98.53,NaN
67,INF092.2,5,5024780,4861420,1,Y,40,16.85,11.36,1276,...,ST2415,KL131,Typeable,NO,NO,NO,FAIL,Klebsiella pneumoniae,1.41,NON_KLEBSIELLA_CONTAMINATION: Enterobacter 95....
68,INF093.1,5,5820577,5228965,1,Y,62,95.54,95.23,1201,...,ST323,KL21,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,96.86,NaN
69,INF093.2,3,5567164,5228924,1,Y,114,91.77,91.19,1270,...,ST323,KL21,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,98.47,NaN
77,INF104.1,2,5499655,5348827,1,Y,68,99.07,98.78,661,...,ST45,KL24,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,97.16,NaN
78,INF104.2,2,5556781,5348835,1,Y,51,99.99,99.75,556,...,ST45,KL24,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,94.79,NaN
87,INF117.1,1,5150283,5150283,1,Y,68,97.47,96.98,354,...,ST3045,KL146,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,98.02,NaN
88,INF117.2,3,5579813,5323609,1,Y,102,90.61,89.48,3500,...,ST3045,KL146,Typeable,YES,NO,NO,PASS,Klebsiella pneumoniae,95.25,NaN
98,INF136.1,5,6020901,5661278,1,Y,53,99.98,99.52,1051,...,ST616,KL54,Typeable,YES,YES,YES,PASS,Klebsiella variicola,95.79,NaN
99,INF136.2,5,6042667,5660325,1,Y,23,99.98,99.54,961,...,ST616,KL54,Typeable,YES,YES,YES,PASS,Klebsiella variicola,91.56,NaN
171,INF254.1,2,5452951,5235370,1,Y,14,98.44,98.35,492,...,ST86,KL2,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,94.43,NaN
172,INF254.2,2,5452556,5235363,1,Y,33,98.42,98.32,314,...,ST86,KL2,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,97.77,NaN
173,INF255.1_v2,9,5692226,5357236,1,Y,195,98.66,98.13,5263,...,ST29,KL30,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,91.06,NaN
174,INF255.2_v2,746,15674009,278058,0,NaN,NaN,97.26,96.16,19662,...,ST29,KL30,Typeable,YES,NO,NO,PASS,Klebsiella pneumoniae,83.20,NaN
176,INF257.1_v2,2,5660285,5448165,1,Y,396,99.62,99.24,1012,...,ST3074,KL13,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,93.32,NaN
177,INF257.2_v2,3,5352327,5178300,1,Y,70,99.65,99.40,1274,...,ST1536,KL30,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,94.03,NaN
209,INF309.1,3,5402087,5196341,1,Y,42,95.97,95.34,497,...,ST1548,KL170,Typeable,YES,YES,YES,PASS,Klebsiella quasipneumoniae,96.98,NaN
210,INF309.2,3,5494832,5195514,1,Y,58,98.29,97.76,496,...,ST1548,KL170,Typeable,YES,YES,YES,PASS,Klebsiella quasipneumoniae,96.42,NaN
214,INF315.1,1,5321793,5321793,1,Y,111,99.96,99.59,469,...,ST3057,KL30,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,97.95,NaN
215,INF315.2,1,5321789,5321789,1,Y,126,99.96,99.59,470,...,ST3057,KL30,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,97.88,NaN
274,KSB1_6I.1,4,5868448,5422762,1,Y,115,99.11,98.59,632,...,ST252,KL81,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,95.40,NaN
275,KSB1_6I.2,3,5851345,5417227,1,Y,86,96.72,96.39,507,...,ST252,KL81,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,95.32,NaN
276,KSB1_7B.1,1,5213139,5213139,1,Y,205,99.93,97.16,6653,...,ST5168,KL21,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,96.16,NaN
277,KSB1_7B.2,3,5050538,4791233,1,Y,216,13.81,9.60,410,...,ST5168,KL21,Typeable,NO,NO,NO,FAIL,Klebsiella pneumoniae,3.95,NON_KLEBSIELLA_CONTAMINATION: Escherichia 76.4...
283,KSB1_8E.1,1,5447832,5447832,1,Y,31,99.22,98.96,354,...,ST2994,KL35,Typeable,YES,YES,YES,PASS,Klebsiella variicola,97.74,NaN
284,KSB1_8E.2,2,5316289,5172158,1,Y,47,12.60,8.49,499,...,ST2994,KL35,Typeable,NO,NO,NO,FAIL,Klebsiella variicola,7.41,NON_KLEBSIELLA_CONTAMINATION: Escherichia 86.9...
303,KSB2_6B.1,4,5467936,5133195,1,N,103,99.98,99.79,671,...,ST215,KL16,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,96.43,NaN
304,KSB2_6B.2,3,4819632,4757536,1,Y,133,11.69,7.68,457,...,ST215,KL16,Typeable,NO,NO,NO,FAIL,Klebsiella pneumoniae,6.67,NON_KLEBSIELLA_CONTAMINATION: Escherichia 81.0...
314,KSB2_10C.1,3,5484763,5260662,1,Y,68,99.51,99.27,356,...,ST661,KL24,Typeable,YES,YES,YES,PASS,Klebsiella pneumoniae,95.82,NaN
315,KSB2_10C.2,3,5033183,4865102,1,Y,153,11.79,7.72,617,...,ST661,KL24,Typeable,NO,NO,NO,FAIL,Klebsiella pneumoniae,0.66,NON_KLEBSIELLA_CONTAMINATION: Escherichia 85.7...

In [10]:
# Variants - manual
# INF001 - keep .1
# INF071 -

In [11]:
# Assign FAIL/PASS/RETRY to all samples based on the above decisions
QC_DECISION = {
    # --- variant of an already-kept strain: QC otherwise fine, drop as duplicate
    "INF001.2":     "FAIL_VARIANT",
    "INF071.2":     "FAIL_VARIANT",
    "INF092.2":     "FAIL_VARIANT",
    "INF093.2":     "FAIL_VARIANT",
    "INF117.2":     "FAIL_VARIANT",
    "INF255.2_v2":  "FAIL_VARIANT",
    "KSB1_7B.2":    "FAIL_VARIANT",
    "KSB1_8E.2":    "FAIL_VARIANT",
    "KSB2_6B.2":    "FAIL_VARIANT",
    "KSB2_10C.2":   "FAIL_VARIANT",

    # --- mapped_pct marginally under threshold, everything else clean
    "INF050":       "PASS_BORDERLINE_MAPPING",
    "INF340":       "PASS_BORDERLINE_MAPPING",
    "KSB1_5C":      "PASS_BORDERLINE_MAPPING",

    # --- E. coli "contamination" traced to a plasmid -> false positive
    "INF184":       "PASS_FALSE_POSITIVE_CONTAM",
    "INF269":       "PASS_FALSE_POSITIVE_CONTAM",

    # --- kraken2 calls mixed Klebsiella, no supporting evidence: provisional pass,
    #     revisit against the external reference typing
    "INF195":       "PASS_PROVISIONAL_CHECK_EXTERNAL",
    "KSB1_2F":      "PASS_PROVISIONAL_CHECK_EXTERNAL",
    "KSB1_3I":      "PASS_PROVISIONAL_CHECK_EXTERNAL",
    "KSB1_6D_v2":   "PASS_PROVISIONAL_CHECK_EXTERNAL",

    # --- genuine intra-genus mixture: decontaminate reads, then reassemble
    "INF186":       "REDO_DECONTAM_KLEBSIELLA",
    "INF216":       "REDO_DECONTAM_KLEBSIELLA",
    "INF262_v2":    "REDO_DECONTAM_KLEBSIELLA",
    "KSB2_5D_v2":   "REDO_DECONTAM_KLEBSIELLA",   # bad assembly overall

    # --- genuine E. coli contamination: decontaminate reads, then reassemble
    "KSB1_2I":      "REDO_DECONTAM_ECOLI",
    "KSB2_4A":      "REDO_DECONTAM_ECOLI",

    # --- assembly-quality problems only: re-run flye with --meta
    "INF096":       "REDO_ASSEMBLY_META",   # >30 contigs
    "INF205":       "REDO_ASSEMBLY_META",   # no chromosomal contig
    "INF294":       "REDO_ASSEMBLY_META",   # k_locus discordant, 23 contigs
    
}

In [12]:
df['internal_qc_decision'] = df['sample'].map(QC_DECISION).fillna("PASS")

In [13]:
df.to_csv("internal_qc_summary.tsv", sep="\t", index=False)