In [1]:
from pathlib import Path

import pandas as pd

TABLES = Path("../pipeline_tables")   # the stage summary tables this repo ships

In [5]:
# FOR DRAFT V3 - Hybrid vs illumina sequence gain/loss
# compute per-isolate hybrid_total_len − illumina_total_len and report mean, SD and range

ill_stats = pd.read_csv(TABLES / "assembly_stats.tsv", sep="\t")
ill_stats['library'] = ill_stats['file'].str.split("/").str[1]
ill_stats['strategy'] = ill_stats['file'].str.split("/").str[2]

# Get only illumina asm
ill_stats = ill_stats[ill_stats['strategy'] == 'illumina_unicycler']

In [6]:
ill_stats

,file,format,type,num_seqs,sum_len,min_len,avg_len,max_len,Q1,Q2,...,sum_gap,N50,N50_num,Q20(%),Q30(%),AvgQual,GC(%),sum_n,library,strategy
1,assemblies/INF001.1/illumina_unicycler/assembl...,FASTA,DNA,93,5610639,103,60329.5,709292,146,453,...,0,491735,5,0,0,0.0,57.36,0,INF001.1,illumina_unicycler
3,assemblies/INF001.2/illumina_unicycler/assembl...,FASTA,DNA,93,5610639,103,60329.5,709292,146,453,...,0,491735,5,0,0,0.0,57.36,0,INF001.2,illumina_unicycler
5,assemblies/INF002/illumina_unicycler/assembly....,FASTA,DNA,91,5608571,100,61632.6,853065,144,511,...,0,355107,6,0,0,0.0,57.24,0,INF002,illumina_unicycler
7,assemblies/INF003/illumina_unicycler/assembly....,FASTA,DNA,105,5479274,102,52183.6,1325635,197,602,...,0,472631,4,0,0,0.0,57.26,0,INF003,illumina_unicycler
9,assemblies/INF004/illumina_unicycler/assembly....,FASTA,DNA,66,5318073,104,80576.9,1006325,192,522,...,0,471749,5,0,0,0.0,57.27,0,INF004,illumina_unicycler
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,assemblies/KSB2_8A/illumina_unicycler/assembly...,FASTA,DNA,69,5402409,100,78295.8,1099638,153,416,...,0,417023,5,0,0,0.0,57.13,0,KSB2_8A,illumina_unicycler
625,assemblies/KSB2_8C/illumina_unicycler/assembly...,FASTA,DNA,115,5155010,106,44826.2,903007,180,257,...,0,369914,5,0,0,0.0,57.59,0,KSB2_8C,illumina_unicycler
627,assemblies/KSB2_8D/illumina_unicycler/assembly...,FASTA,DNA,135,5541371,100,41047.2,931351,206,948,...,0,343071,5,0,0,0.0,57.12,0,KSB2_8D,illumina_unicycler
629,assemblies/KSB2_9B/illumina_unicycler/assembly...,FASTA,DNA,180,5511361,101,30618.7,745069,157,311,...,0,192058,9,0,0,0.0,57.22,0,KSB2_9B,illumina_unicycler
631,assemblies/KSB2_9C/illumina_unicycler/assembly...,FASTA,DNA,70,5270348,114,75290.7,858347,167,630,...,0,430497,5,0,0,0.0,57.50,0,KSB2_9C,illumina_unicycler

In [7]:
hybrid_stats = pd.read_csv("hybrid_stats.tsv", sep="\t")

In [12]:
# remove _polca.fasta suffix (and _v2_polca.fasta) to match illumina library names
hybrid_stats['library'] = hybrid_stats['file'].str.split("/").str[-1].str.replace("_polca.fasta", "").str.replace("_v2_polca.fasta", "")

In [18]:
# compute per-isolate hybrid_total_len − illumina_total_len and report mean, SD and range.
len_diff = []

for lib in hybrid_stats['library']:
    hybrid_len = hybrid_stats[hybrid_stats['library'] == lib]['sum_len'].values[0]
    ill_len = ill_stats[ill_stats['library'] == lib]['sum_len'].values[0]
    len_diff.append(hybrid_len - ill_len)

# compute mean, SD and range
import numpy as np

mean_diff = np.mean(len_diff)
std_diff = np.std(len_diff)
range_diff = (np.min(len_diff), np.max(len_diff))

print(f"Mean difference: {mean_diff}")
print(f"Standard deviation: {std_diff}")
print(f"Range: {range_diff}")

Mean difference: 79601.46575342465
Standard deviation: 58648.24458970879
Range: (np.int64(-122951), np.int64(426272))

,file,format,type,num_seqs,sum_len,min_len,avg_len,max_len,Q1,Q2,...,sum_gap,N50,N50_num,Q20(%),Q30(%),AvgQual,GC(%),sum_n,library,strategy
1,assemblies/INF001.1/illumina_unicycler/assembl...,FASTA,DNA,93,5610639,103,60329.5,709292,146,453,...,0,491735,5,0,0,0.0,57.36,0,INF001.1,illumina_unicycler
3,assemblies/INF001.2/illumina_unicycler/assembl...,FASTA,DNA,93,5610639,103,60329.5,709292,146,453,...,0,491735,5,0,0,0.0,57.36,0,INF001.2,illumina_unicycler
5,assemblies/INF002/illumina_unicycler/assembly....,FASTA,DNA,91,5608571,100,61632.6,853065,144,511,...,0,355107,6,0,0,0.0,57.24,0,INF002,illumina_unicycler
7,assemblies/INF003/illumina_unicycler/assembly....,FASTA,DNA,105,5479274,102,52183.6,1325635,197,602,...,0,472631,4,0,0,0.0,57.26,0,INF003,illumina_unicycler
9,assemblies/INF004/illumina_unicycler/assembly....,FASTA,DNA,66,5318073,104,80576.9,1006325,192,522,...,0,471749,5,0,0,0.0,57.27,0,INF004,illumina_unicycler
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,assemblies/KSB2_8A/illumina_unicycler/assembly...,FASTA,DNA,69,5402409,100,78295.8,1099638,153,416,...,0,417023,5,0,0,0.0,57.13,0,KSB2_8A,illumina_unicycler
625,assemblies/KSB2_8C/illumina_unicycler/assembly...,FASTA,DNA,115,5155010,106,44826.2,903007,180,257,...,0,369914,5,0,0,0.0,57.59,0,KSB2_8C,illumina_unicycler
627,assemblies/KSB2_8D/illumina_unicycler/assembly...,FASTA,DNA,135,5541371,100,41047.2,931351,206,948,...,0,343071,5,0,0,0.0,57.12,0,KSB2_8D,illumina_unicycler
629,assemblies/KSB2_9B/illumina_unicycler/assembly...,FASTA,DNA,180,5511361,101,30618.7,745069,157,311,...,0,192058,9,0,0,0.0,57.22,0,KSB2_9B,illumina_unicycler
631,assemblies/KSB2_9C/illumina_unicycler/assembly...,FASTA,DNA,70,5270348,114,75290.7,858347,167,630,...,0,430497,5,0,0,0.0,57.50,0,KSB2_9C,illumina_unicycler